name: Build x64

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Set up Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: pwsh
        run: ./build.ps1 64 Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/64/Release/*.dll

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: ./build/64/Release/*.dll
